la til s3.tf

diff --git a/.github/workflows/cloudwatch_dashboard.yml b/.github/workflows/cloudwatch_dashboard.yml
--- a/.github/workflows/cloudwatch_dashboard.yml
+++ b/.github/workflows/cloudwatch_dashboard.yml
@@ -40,57 +40,57 @@ jobs:
         if: github.ref == 'refs/heads/master' && github.event_name == 'push'
         run: terraform apply -var="candidate_id=$CANDIDATE_ID" -var="candidate_email=$CANDIDATE_EMAIL"  -auto-approve
 
-      - uses: actions/github-script@0.9.0
-        if: github.event_name == 'pull_request'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-            <details><summary>Show Plan</summary>
-            \n
-            \`\`\`\n
-            ${process.env.PLAN}
-            \`\`\`
-            </details>
-            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-            github.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
-
-            #Pull
-
-            - name: Terraform Plan Status
-              if: steps.plan.outcome == 'failure'
-              run: exit 1
-
-            - name: Terraform Apply
-              if: github.ref == 'refs/heads/master' && github.event_name == 'push'
-              run: terraform apply -auto-approve
-              working-directory: ${{ env.working-directory }}
-
-            onlinestore:
-              env:
-                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-                AWS_REGION: eu-west-1
-              needs: terraform
-              runs-on: ubuntu-latest
-              steps:
-                - uses: actions/checkout@v2
-                - uses: actions/setup-node@v2
-                  with:
-                    node-version: '14'
-                - run: npm install
-                  # working-directory: ./demo-app
-                - run: npm run build
-                  # working-directory: ./demo-app
-                - run: aws s3 cp build s3://analytics-1045 --recursive --region eu-west-1
-                  # working-directory: ./demo-app
+#      - uses: actions/github-script@0.9.0
+#        if: github.event_name == 'pull_request'
+#        env:
+#          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+#        with:
+#          github-token: ${{ secrets.GITHUB_TOKEN }}
+#          script: |
+#            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+#            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+#            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+#            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+#            <details><summary>Show Plan</summary>
+#            \n
+#            \`\`\`\n
+#            ${process.env.PLAN}
+#            \`\`\`
+#            </details>
+#            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+#            github.issues.createComment({
+#              issue_number: context.issue.number,
+#              owner: context.repo.owner,
+#              repo: context.repo.repo,
+#              body: output
+#            })
+#
+#            #Pull
+#
+#            - name: Terraform Plan Status
+#              if: steps.plan.outcome == 'failure'
+#              run: exit 1
+#
+#            - name: Terraform Apply
+#              if: github.ref == 'refs/heads/master' && github.event_name == 'push'
+#              run: terraform apply -auto-approve
+#              working-directory: ${{ env.working-directory }}
+#
+#            onlinestore:
+#              env:
+#                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#                AWS_REGION: eu-west-1
+#              needs: terraform
+#              runs-on: ubuntu-latest
+#              steps:
+#                - uses: actions/checkout@v2
+#                - uses: actions/setup-node@v2
+#                  with:
+#                    node-version: '14'
+#                - run: npm install
+#                  # working-directory: ./demo-app
+#                - run: npm run build
+#                  # working-directory: ./demo-app
+#                - run: aws s3 cp build s3://analytics-1045 --recursive --region eu-west-1
+#                  # working-directory: ./demo-app
